# Generated by Django 5.0.6 on 2024-07-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('required_age', models.IntegerField()),
                ('price', models.FloatField()),
                ('dlc_count', models.IntegerField()),
                ('about_the_game', models.TextField()),
                ('supported_languages', models.JSONField()),
                ('windows', models.BooleanField()),
                ('mac', models.BooleanField()),
                ('linux', models.BooleanField()),
                ('positive_reviews', models.IntegerField()),
                ('negative_reviews', models.IntegerField()),
                ('score_rank', models.IntegerField()),
                ('developers', models.CharField(max_length=255)),
                ('publishers', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
            ],
        ),
    ]
