# Generated by Django 5.0.6 on 2024-07-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
