# Generated by Django 5.0.6 on 2024-07-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_game_score_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='app_id',
            field=models.IntegerField(),
        ),
    ]
