# Generated by Django 5.0.6 on 2024-07-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_game_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='about_the_game',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='app_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='developers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='dlc_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='linux',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='mac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='negative_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='positive_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='publishers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='required_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='supported_languages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='windows',
            field=models.BooleanField(default=False),
        ),
    ]
